name: Ejecutar Proyecto Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ejecutar-nodo:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código del repositorio
      uses: actions/checkout@v4

    # Aquí configuramos exactamente tu versión local v24.16.0
    - name: Configurar Node.js (Versión Local)
      uses: actions/setup-node@v4
      with:
        node-version: '24.16.0'

    - name: Ejecutar app.js
      run: node app.js